"""Add unit column to Post table

Revision ID: 69f97c0535f6
Revises:
Create Date: 2025-04-09 11:25:01.948478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f97c0535f6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Add the 'unit' column with a default value
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False, server_default=''))

    # Remove the server_default after the column is added
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('unit', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
